/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo;

import jguiextensible.JGuiSimple;

/**
 *
 * @author a31r1z
 */
public class FuncionesGUI extends JGuiSimple {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form NewBeanForm
     */
    public FuncionesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jchkSelectorZeroAbs = new javax.swing.JCheckBox();
        jchkSalidaDeDatos = new javax.swing.JCheckBox();
        jchkValoracionGoNg = new javax.swing.JCheckBox();
        jchkBloqueo = new javax.swing.JCheckBox();
        jchkCambioSentidoContaje = new javax.swing.JCheckBox();
        jchkAjusteFino = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Funciones opcionales"));

        jchkSelectorZeroAbs.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jchkSelectorZeroAbs.setText("Selector ZERO/ABS");

        jchkSalidaDeDatos.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jchkSalidaDeDatos.setText("Salida de datos");

        jchkValoracionGoNg.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jchkValoracionGoNg.setText("Valoracion GO/+-NG");

        jchkBloqueo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jchkBloqueo.setText("Bloqueo");

        jchkCambioSentidoContaje.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jchkCambioSentidoContaje.setText("Cambio sentido contaje");

        jchkAjusteFino.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jchkAjusteFino.setText("Ajuste fino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkSelectorZeroAbs)
                    .addComponent(jchkCambioSentidoContaje)
                    .addComponent(jchkSalidaDeDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkBloqueo)
                    .addComponent(jchkValoracionGoNg)
                    .addComponent(jchkAjusteFino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jchkAjusteFino, jchkBloqueo, jchkCambioSentidoContaje, jchkSalidaDeDatos, jchkSelectorZeroAbs, jchkValoracionGoNg});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkSelectorZeroAbs)
                    .addComponent(jchkValoracionGoNg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkSalidaDeDatos)
                    .addComponent(jchkBloqueo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkCambioSentidoContaje)
                    .addComponent(jchkAjusteFino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jchkAjusteFino;
    private javax.swing.JCheckBox jchkBloqueo;
    private javax.swing.JCheckBox jchkCambioSentidoContaje;
    private javax.swing.JCheckBox jchkSalidaDeDatos;
    private javax.swing.JCheckBox jchkSelectorZeroAbs;
    private javax.swing.JCheckBox jchkValoracionGoNg;
    // End of variables declaration//GEN-END:variables
}
