/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo;

import jguiextensible.JGuiSimple;

/**
 *
 * @author a31r1z
 */
public class MetricaComparadorGUI extends JGuiSimple {

    /**
     * Creates new form MetricaComparador
     */
    public MetricaComparadorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRangoMedida = new javax.swing.JLabel();
        jslidRangoMedida = new javax.swing.JSlider();
        lblErrorMaximo = new javax.swing.JLabel();
        lblHyteresis = new javax.swing.JLabel();
        lblEscala = new javax.swing.JLabel();
        jtxtErrorMax = new javax.swing.JTextField();
        jtxtHyteresis = new javax.swing.JTextField();
        jtxtEscala = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica de Comparador"));
        setName("Comparador"); // NOI18N

        lblRangoMedida.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRangoMedida.setText("Rango de medida");

        lblErrorMaximo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblErrorMaximo.setText("Error max. permitido");

        lblHyteresis.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblHyteresis.setText("Hyteresis (mm)");

        lblEscala.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblEscala.setText("Escala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHyteresis)
                    .addComponent(lblRangoMedida)
                    .addComponent(lblEscala)
                    .addComponent(lblErrorMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jslidRangoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtHyteresis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtErrorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtErrorMax, jtxtEscala, jtxtHyteresis});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jslidRangoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRangoMedida))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorMaximo)
                    .addComponent(jtxtErrorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHyteresis)
                    .addComponent(jtxtHyteresis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscala)
                    .addComponent(jtxtEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jslidRangoMedida;
    private javax.swing.JTextField jtxtErrorMax;
    private javax.swing.JTextField jtxtEscala;
    private javax.swing.JTextField jtxtHyteresis;
    private javax.swing.JLabel lblErrorMaximo;
    private javax.swing.JLabel lblEscala;
    private javax.swing.JLabel lblHyteresis;
    private javax.swing.JLabel lblRangoMedida;
    // End of variables declaration//GEN-END:variables
}
