/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo;

import jguiextensible.JGuiSimple;

/**
 *
 * @author a31r1z
 */
public class MetricaDeInterioresGUI extends JGuiSimple {

    /**
     * Creates new form MetricaDeInteriores
     */
    public MetricaDeInterioresGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedida_R = new javax.swing.JLabel();
        lblMedida_f = new javax.swing.JLabel();
        lblMedida_g = new javax.swing.JLabel();
        jtxtMedida_R = new javax.swing.JTextField();
        jtxtMedida_f = new javax.swing.JTextField();
        jtxtMedida_g = new javax.swing.JTextField();
        jcbxPuntosMedicion = new javax.swing.JComboBox<>();
        jlblPuntosMedicion = new javax.swing.JLabel();
        lblMedicionInterior = new javax.swing.JLabel();
        jtxtMedicionInterior = new javax.swing.JTextField();
        lblRangoInterior = new javax.swing.JLabel();
        jtxtRangoInterior = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica de interiores"));
        setName("Micrometro de interiores"); // NOI18N

        lblMedida_R.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_R.setText("R (mm)");

        lblMedida_f.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_f.setText("f (mm)");

        lblMedida_g.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_g.setText("g (mm)");

        jcbxPuntosMedicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " " }));

        jlblPuntosMedicion.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jlblPuntosMedicion.setText("Puntos de medicion");

        lblMedicionInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedicionInterior.setText("Medicion interior desde");

        lblRangoInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRangoInterior.setText("Rango Interior (mm)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRangoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida_R))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtRangoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMedida_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMedicionInterior)
                    .addComponent(jlblPuntosMedicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMedida_f)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtMedida_R, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMedida_g)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtMedida_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtMedicionInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbxPuntosMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtMedicionInterior, jtxtMedida_R, jtxtMedida_f, jtxtMedida_g});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlblPuntosMedicion, lblMedicionInterior});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRangoInterior)
                    .addComponent(jtxtRangoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMedida_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_g))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedida_R)
                    .addComponent(jtxtMedida_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMedida_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_f))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicionInterior)
                    .addComponent(jtxtMedicionInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPuntosMedicion)
                    .addComponent(jcbxPuntosMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcbxPuntosMedicion;
    private javax.swing.JLabel jlblPuntosMedicion;
    private javax.swing.JTextField jtxtMedicionInterior;
    private javax.swing.JTextField jtxtMedida_R;
    private javax.swing.JTextField jtxtMedida_f;
    private javax.swing.JTextField jtxtMedida_g;
    private javax.swing.JTextField jtxtRangoInterior;
    private javax.swing.JLabel lblMedicionInterior;
    private javax.swing.JLabel lblMedida_R;
    private javax.swing.JLabel lblMedida_f;
    private javax.swing.JLabel lblMedida_g;
    private javax.swing.JLabel lblRangoInterior;
    // End of variables declaration//GEN-END:variables
}
