/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo;

import jguiextensible.JGuiTabbed;

/**
 *
 * @author a31r1z
 */
public class MetricaMicrometricaGUI extends JGuiTabbed {

    /**
     * Creates new form MetricaMicrometrica
     */
    public MetricaMicrometricaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvance = new javax.swing.JLabel();
        lblPlanitud = new javax.swing.JLabel();
        lblParalelismo = new javax.swing.JLabel();
        lblPerpendicularidad = new javax.swing.JLabel();
        lblRectitud = new javax.swing.JLabel();
        jtxtAvance = new javax.swing.JTextField();
        jtxtPlanitud = new javax.swing.JTextField();
        jtxtParalelismo = new javax.swing.JTextField();
        jtxtPerpendicularidad = new javax.swing.JTextField();
        jtxtRectitud = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica micrometrica"));

        lblAvance.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblAvance.setText("Avance ± (µm)");

        lblPlanitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPlanitud.setText("Planitud (µm)");

        lblParalelismo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblParalelismo.setText("Paralelismo (µm)");

        lblPerpendicularidad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPerpendicularidad.setText("Perpendicularidad (µm)");

        lblRectitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRectitud.setText("Rectitud (µm)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParalelismo)
                    .addComponent(lblPerpendicularidad)
                    .addComponent(lblRectitud)
                    .addComponent(lblAvance)
                    .addComponent(lblPlanitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPlanitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtParalelismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPerpendicularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRectitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtAvance, jtxtParalelismo, jtxtPerpendicularidad, jtxtPlanitud, jtxtRectitud});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtAvance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlanitud, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtPlanitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParalelismo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtParalelismo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerpendicularidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtPerpendicularidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRectitud, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtRectitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtxtAvance;
    private javax.swing.JTextField jtxtParalelismo;
    private javax.swing.JTextField jtxtPerpendicularidad;
    private javax.swing.JTextField jtxtPlanitud;
    private javax.swing.JTextField jtxtRectitud;
    private javax.swing.JLabel lblAvance;
    private javax.swing.JLabel lblParalelismo;
    private javax.swing.JLabel lblPerpendicularidad;
    private javax.swing.JLabel lblPlanitud;
    private javax.swing.JLabel lblRectitud;
    // End of variables declaration//GEN-END:variables
}
