/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo.interfaces;

import jguiextensible.JGuiSimple;

/**
 *
 * @author a31r1z
 */
public class DimensionesGUI extends JGuiSimple {

    private static final long serialVersionUID = 1L;
  
   
    /**
     * Creates new form CalibreGui
     */
    public DimensionesGUI() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDimensiones = new javax.swing.JPanel();
        lblLongitud = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblMedida_b = new javax.swing.JLabel();
        lblMedida_d = new javax.swing.JLabel();
        lblMedida_a = new javax.swing.JLabel();
        lblMedida_c = new javax.swing.JLabel();
        lblMedida_e = new javax.swing.JLabel();
        jftxLongitud = new javax.swing.JFormattedTextField();
        jftxPeso = new javax.swing.JFormattedTextField();
        jftxMedida_b = new javax.swing.JFormattedTextField();
        jftxMedida_d = new javax.swing.JFormattedTextField();
        jftxMedida_a = new javax.swing.JFormattedTextField();
        jftxMedida_c = new javax.swing.JFormattedTextField();
        jftxMedida_e = new javax.swing.JFormattedTextField();

        setName("Dimensiones"); // NOI18N

        panelDimensiones.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensiones"));
        panelDimensiones.setOpaque(false);

        lblLongitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblLongitud.setText("Longitud [mm]");

        lblPeso.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPeso.setText("Peso [gr]");

        lblMedida_b.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_b.setText("b [mm]");

        lblMedida_d.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_d.setText("d [mm]");

        lblMedida_a.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_a.setText("a [mm]");

        lblMedida_c.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_c.setText("c [mm]");

        lblMedida_e.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_e.setText("e [mm]");

        jftxLongitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxLongitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxPeso.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_b.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_d.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_d.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_a.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_c.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_e.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_e.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        javax.swing.GroupLayout panelDimensionesLayout = new javax.swing.GroupLayout(panelDimensiones);
        panelDimensiones.setLayout(panelDimensionesLayout);
        panelDimensionesLayout.setHorizontalGroup(
            panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDimensionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDimensionesLayout.createSequentialGroup()
                        .addComponent(lblMedida_b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftxMedida_b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblMedida_c, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jftxMedida_c, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDimensionesLayout.createSequentialGroup()
                        .addComponent(lblMedida_d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftxMedida_d, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblMedida_e)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jftxMedida_e, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDimensionesLayout.createSequentialGroup()
                        .addGroup(panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDimensionesLayout.createSequentialGroup()
                                .addComponent(lblLongitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftxLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDimensionesLayout.createSequentialGroup()
                                .addComponent(lblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblMedida_a, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftxMedida_a, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDimensionesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblMedida_a, lblMedida_c, lblMedida_e});

        panelDimensionesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblLongitud, lblMedida_b, lblMedida_d, lblPeso});

        panelDimensionesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxLongitud, jftxMedida_a, jftxMedida_b, jftxMedida_c, jftxMedida_d, jftxMedida_e, jftxPeso});

        panelDimensionesLayout.setVerticalGroup(
            panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDimensionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLongitud)
                    .addComponent(jftxLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPeso)
                    .addComponent(jftxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_a)
                    .addComponent(jftxMedida_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMedida_b)
                    .addComponent(jftxMedida_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_c)
                    .addComponent(jftxMedida_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMedida_d)
                    .addComponent(jftxMedida_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_e)
                    .addComponent(jftxMedida_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelDimensiones);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jftxLongitud;
    private javax.swing.JFormattedTextField jftxMedida_a;
    private javax.swing.JFormattedTextField jftxMedida_b;
    private javax.swing.JFormattedTextField jftxMedida_c;
    private javax.swing.JFormattedTextField jftxMedida_d;
    private javax.swing.JFormattedTextField jftxMedida_e;
    private javax.swing.JFormattedTextField jftxPeso;
    private javax.swing.JLabel lblLongitud;
    private javax.swing.JLabel lblMedida_a;
    private javax.swing.JLabel lblMedida_b;
    private javax.swing.JLabel lblMedida_c;
    private javax.swing.JLabel lblMedida_d;
    private javax.swing.JLabel lblMedida_e;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JPanel panelDimensiones;
    // End of variables declaration//GEN-END:variables

    @Override
   protected boolean validacion() {
     
       if (jftxLongitud.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Longitud");
            jftxLongitud.requestFocusInWindow();
        
            return false;
        }   
       
        if (jftxMedida_a.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Medida_a");
            jftxMedida_a.requestFocusInWindow();
        
            return false;
        }   
        
        if (jftxMedida_b.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Medida_b");
            jftxMedida_b.requestFocusInWindow();
        
            return false;
        }   
        
        if (jftxMedida_c.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Medida_c");
            jftxMedida_c.requestFocusInWindow();
        
            return false;
        }   
        
        if (jftxMedida_d.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Medida_d");
            jftxMedida_d.requestFocusInWindow();
        
            return false;
        }   
        
        if (jftxMedida_e.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Medida_e");
            jftxMedida_e.requestFocusInWindow();
        
            return false;
        }   
        
        if (jftxPeso.getValue() == null){
            
             Validar.mostrar("ERROR: Faltan datos en:\n "
                          + this.getName() +"-> Peso");
            jftxPeso.requestFocusInWindow();
        
            return false;
        }   
       
        
    return true;    
   }

    @Override
   protected void actualizarCambio(String id, Object value) {}
}
