/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo.interfaces;

import java.beans.PropertyChangeListener;
import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;
import jguiextensible.JGuiSimple;

/**
 *
 * @author a31r1z
 */
public class MetricaComparadorGUI extends JGuiSimple {

    private MetricaComparador mtComp = new MetricaComparador();
   
    /**
     * Creates new form MetricaComparador
     */
    public MetricaComparadorGUI() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jguiMetricaComp = new jguiextensible.JGuiSimple();
        jfxtErrorMax = new javax.swing.JFormattedTextField();
        jsldRangoMedida = new javax.swing.JSlider();
        lblErrorMaximo = new javax.swing.JLabel();
        lblRangoMedida = new javax.swing.JLabel();
        lblHyteresis = new javax.swing.JLabel();
        jfxtHyteresis = new javax.swing.JFormattedTextField();
        jftxtEscala = new javax.swing.JFormattedTextField();
        lblEscala = new javax.swing.JLabel();

        jFormattedTextField2.setText("jFormattedTextField2");

        setName("Metrica Comparador"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jguiMetricaComp.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica comparativa"));

        jfxtErrorMax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jfxtErrorMax.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jfxtErrorMax.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jfxtErrorMaxPropertyChange(evt);
            }
        });

        jsldRangoMedida.setFont(new java.awt.Font("URW Gothic", 0, 12)); // NOI18N
        jsldRangoMedida.setMajorTickSpacing(10);
        jsldRangoMedida.setMaximum(50);
        jsldRangoMedida.setMinorTickSpacing(5);
        jsldRangoMedida.setPaintLabels(true);
        jsldRangoMedida.setPaintTicks(true);
        jsldRangoMedida.setSnapToTicks(true);
        jsldRangoMedida.setValue(25);
        jsldRangoMedida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldRangoMedidaStateChanged(evt);
            }
        });

        lblErrorMaximo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblErrorMaximo.setText("Error max. permitido");

        lblRangoMedida.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRangoMedida.setText("Rango de medida");

        lblHyteresis.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblHyteresis.setText("Hyteresis (mm)");

        jfxtHyteresis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jfxtHyteresis.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxtEscala.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        lblEscala.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblEscala.setText("Escala");

        javax.swing.GroupLayout jguiMetricaCompLayout = new javax.swing.GroupLayout(jguiMetricaComp);
        jguiMetricaComp.setLayout(jguiMetricaCompLayout);
        jguiMetricaCompLayout.setHorizontalGroup(
            jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblErrorMaximo))
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRangoMedida))
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHyteresis))
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEscala)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsldRangoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftxtEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfxtErrorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfxtHyteresis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jguiMetricaCompLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxtEscala, jfxtErrorMax, jfxtHyteresis});

        jguiMetricaCompLayout.setVerticalGroup(
            jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblRangoMedida))
                    .addComponent(jsldRangoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMaximo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxtEscala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHyteresis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfxtErrorMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEscala, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfxtHyteresis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jguiMetricaCompLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jftxtEscala, jfxtErrorMax, jfxtHyteresis});

        add(jguiMetricaComp);
    }// </editor-fold>//GEN-END:initComponents

    private void jsldRangoMedidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldRangoMedidaStateChanged
       
        
        //mtComp.setRangoMedida(jsldRangoMedida.getValue());
       this.notificarCambio("rangoMedida", jsldRangoMedida.getValue());
         
    }//GEN-LAST:event_jsldRangoMedidaStateChanged

    private void jfxtErrorMaxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jfxtErrorMaxPropertyChange
    
        if(jfxtErrorMax.getValue() !=null) {
            
            Integer value = ((Number)jfxtErrorMax.getValue()).intValue();
            mtComp.setErrorMax(value);
            notificarCambio(MetricaComparador.PROP_ERRORMAX, mtComp.getErrorMax());
        }
    }//GEN-LAST:event_jfxtErrorMaxPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JFormattedTextField jFormattedTextField2;
    javax.swing.JFormattedTextField jftxtEscala;
    javax.swing.JFormattedTextField jfxtErrorMax;
    javax.swing.JFormattedTextField jfxtHyteresis;
    jguiextensible.JGuiSimple jguiMetricaComp;
    javax.swing.JSlider jsldRangoMedida;
    javax.swing.JLabel lblErrorMaximo;
    javax.swing.JLabel lblEscala;
    javax.swing.JLabel lblHyteresis;
    javax.swing.JLabel lblRangoMedida;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void actualizarCambio(String id, Object obj) {}
}
