/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo.interfaces;

import javax.swing.JOptionPane;
import jguiextensible.JGuiSimple;
import jguiextensible.JGuiTree;

/**
 *
 * @author a31r1z
 */
public class MetricaDeInterioresGUI extends JGuiSimple {

    private boolean existRangoInt = false;
    /**
     * Creates new form MetricaInterior
     */
    public MetricaDeInterioresGUI() {
        
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jguiMetricaDeInteriores = new jguiextensible.JGuiSimple();
        lblRangoInterior = new javax.swing.JLabel();
        lblMedida_R = new javax.swing.JLabel();
        lblMedida_f = new javax.swing.JLabel();
        lblMedida_g = new javax.swing.JLabel();
        lblMetricaInterior = new javax.swing.JLabel();
        lblPuntosMediciion = new javax.swing.JLabel();
        jftxRangoInterior = new javax.swing.JFormattedTextField();
        jftxMetrica_f = new javax.swing.JFormattedTextField();
        jftxMedida_g = new javax.swing.JFormattedTextField();
        jftxMedida_R = new javax.swing.JFormattedTextField();
        jftxMetricaInterior = new javax.swing.JFormattedTextField();
        jcboxPuntosMedicion = new javax.swing.JComboBox<>();

        setName("Metrica de Interiores"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jguiMetricaDeInteriores.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica de interiores"));
        jguiMetricaDeInteriores.setName("Metrica de Interiores"); // NOI18N

        lblRangoInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRangoInterior.setText("Rango interior (mm)");

        lblMedida_R.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_R.setText("R (mm)");

        lblMedida_f.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_f.setText("f (mm)");

        lblMedida_g.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_g.setText("g (mm)");

        lblMetricaInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMetricaInterior.setText("Metrica interior desde");

        lblPuntosMediciion.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPuntosMediciion.setText("Puntos de medicion");

        jftxRangoInterior.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxRangoInterior.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jftxRangoInteriorPropertyChange(evt);
            }
        });

        jftxMetrica_f.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jftxMedida_g.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jftxMedida_R.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jftxMetricaInterior.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jcboxPuntosMedicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout jguiMetricaDeInterioresLayout = new javax.swing.GroupLayout(jguiMetricaDeInteriores);
        jguiMetricaDeInteriores.setLayout(jguiMetricaDeInterioresLayout);
        jguiMetricaDeInterioresLayout.setHorizontalGroup(
            jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                                .addComponent(lblRangoInterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jftxRangoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMetricaInterior)
                                    .addComponent(lblPuntosMediciion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcboxPuntosMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jftxMetricaInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                        .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedida_R, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedida_f, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jguiMetricaDeInterioresLayout.createSequentialGroup()
                        .addContainerGap(263, Short.MAX_VALUE)
                        .addComponent(lblMedida_g)))
                .addGap(18, 18, 18)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxMedida_R, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxMetrica_f, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxMedida_g, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jguiMetricaDeInterioresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxMedida_R, jftxMedida_g, jftxMetricaInterior, jftxMetrica_f, jftxRangoInterior});

        jguiMetricaDeInterioresLayout.setVerticalGroup(
            jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblRangoInterior)
                    .addComponent(jftxRangoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_R)
                    .addComponent(jftxMedida_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMetricaInterior)
                    .addComponent(jftxMetricaInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_f)
                    .addComponent(jftxMetrica_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPuntosMediciion)
                    .addComponent(jcboxPuntosMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_g)
                    .addComponent(jftxMedida_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jguiMetricaDeInteriores);
    }// </editor-fold>//GEN-END:initComponents

    private void jftxRangoInteriorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jftxRangoInteriorPropertyChange
       
        existRangoInt = jftxRangoInterior.getValue() != null;
     
        System.out.println(existRangoInt);
    }//GEN-LAST:event_jftxRangoInteriorPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcboxPuntosMedicion;
    private javax.swing.JFormattedTextField jftxMedida_R;
    private javax.swing.JFormattedTextField jftxMedida_g;
    private javax.swing.JFormattedTextField jftxMetricaInterior;
    private javax.swing.JFormattedTextField jftxMetrica_f;
    private javax.swing.JFormattedTextField jftxRangoInterior;
    private jguiextensible.JGuiSimple jguiMetricaDeInteriores;
    private javax.swing.JLabel lblMedida_R;
    private javax.swing.JLabel lblMedida_f;
    private javax.swing.JLabel lblMedida_g;
    private javax.swing.JLabel lblMetricaInterior;
    private javax.swing.JLabel lblPuntosMediciion;
    private javax.swing.JLabel lblRangoInterior;
    // End of variables declaration//GEN-END:variables
    
    @Override
    protected void actualizarCambio(String id, Object obj) { }
    
    @Override
    protected boolean validacion( ) {
        
        /*  if(!validateThis(jftxRangoInterior.getText())) {
        jftxRangoInterior.requestFocusInWindow();
        }
        return false;*/
        
        if (!validateThis(existRangoInt)){
            
            jftxRangoInterior.requestFocusInWindow();
        
            return false;
        }   
        
        return true;
    } 
    
    protected boolean validateThis(boolean arg) {
        
           if (!arg) {
               Validar.mostrar("ERROR: Faltan introducir datos.");
               return false;
           }
     
        return true;     
    }
}
