/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo.interfaces;

import javax.swing.JOptionPane;
import jguiextensible.JGuiSimple;
import jguiextensible.JGuiTree;

/**
 *
 * @author a31r1z
 */
public class MetricaDeInterioresGUI extends JGuiSimple {

    private MetricaDeInteriores metDeInt = new MetricaDeInteriores();
    
    /**
     * Creates new form MetricaInterior
     */
    public MetricaDeInterioresGUI() {
        
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jguiMetricaDeInteriores = new jguiextensible.JGuiSimple();
        lblRangoInterior = new javax.swing.JLabel();
        lblMedida_R = new javax.swing.JLabel();
        lblMedida_f = new javax.swing.JLabel();
        lblMedida_g = new javax.swing.JLabel();
        lblMetricaInterior = new javax.swing.JLabel();
        lblPuntosMediciion = new javax.swing.JLabel();
        jftxRangoInterior = new javax.swing.JFormattedTextField();
        jftxMedida_f = new javax.swing.JFormattedTextField();
        jftxMedida_g = new javax.swing.JFormattedTextField();
        jftxMedida_R = new javax.swing.JFormattedTextField();
        jftxMetricaInterior = new javax.swing.JFormattedTextField();
        jcboxPuntosMedicion = new javax.swing.JComboBox<>();

        setName("Metrica de Interiores"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jguiMetricaDeInteriores.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica de interiores"));
        jguiMetricaDeInteriores.setName("Metrica de Interiores"); // NOI18N

        lblRangoInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRangoInterior.setText("Rango interior (mm)");

        lblMedida_R.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_R.setText("R (mm)");

        lblMedida_f.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_f.setText("f (mm)");

        lblMedida_g.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMedida_g.setText("g (mm)");

        lblMetricaInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMetricaInterior.setText("Metrica interior desde");

        lblPuntosMediciion.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPuntosMediciion.setText("Puntos de medicion");

        jftxRangoInterior.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxRangoInterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxRangoInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_f.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxMedida_f.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_f.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_g.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxMedida_g.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_g.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMedida_R.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxMedida_R.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMedida_R.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxMetricaInterior.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxMetricaInterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxMetricaInterior.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jcboxPuntosMedicion.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jcboxPuntosMedicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "1", "2", "3" }));

        javax.swing.GroupLayout jguiMetricaDeInterioresLayout = new javax.swing.GroupLayout(jguiMetricaDeInteriores);
        jguiMetricaDeInteriores.setLayout(jguiMetricaDeInterioresLayout);
        jguiMetricaDeInterioresLayout.setHorizontalGroup(
            jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetricaInterior)
                    .addComponent(lblRangoInterior)
                    .addComponent(lblPuntosMediciion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jftxMetricaInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jftxRangoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcboxPuntosMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedida_R)
                    .addComponent(lblMedida_f)
                    .addComponent(lblMedida_g))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxMedida_R, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxMedida_f, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxMedida_g, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jguiMetricaDeInterioresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxMedida_R, jftxMedida_f, jftxMedida_g, jftxMetricaInterior, jftxRangoInterior});

        jguiMetricaDeInterioresLayout.setVerticalGroup(
            jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaDeInterioresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRangoInterior, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxRangoInterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_R, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxMedida_R, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetricaInterior, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxMetricaInterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_f, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxMedida_f, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaDeInterioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntosMediciion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcboxPuntosMedicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedida_g, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxMedida_g, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jguiMetricaDeInteriores);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcboxPuntosMedicion;
    private javax.swing.JFormattedTextField jftxMedida_R;
    private javax.swing.JFormattedTextField jftxMedida_f;
    private javax.swing.JFormattedTextField jftxMedida_g;
    private javax.swing.JFormattedTextField jftxMetricaInterior;
    private javax.swing.JFormattedTextField jftxRangoInterior;
    private jguiextensible.JGuiSimple jguiMetricaDeInteriores;
    private javax.swing.JLabel lblMedida_R;
    private javax.swing.JLabel lblMedida_f;
    private javax.swing.JLabel lblMedida_g;
    private javax.swing.JLabel lblMetricaInterior;
    private javax.swing.JLabel lblPuntosMediciion;
    private javax.swing.JLabel lblRangoInterior;
    // End of variables declaration//GEN-END:variables
    
    
    @Override
    protected boolean validarDatos( ) {
    
        return Utilidades.matcher(jftxRangoInterior, "Rango interior",this) &&
               Utilidades.matcher(jftxMedida_R, "Medida_R",this) &&
               Utilidades.matcher(jftxMetricaInterior, "MetricaInterior",this) &&
               Utilidades.matcher(jftxMedida_f, "Medida_f",this) &&
               Utilidades.matcher(jcboxPuntosMedicion, "Puntos de Medicion",this) &&
               Utilidades.matcher(jftxMedida_g, "Medida_g",this) ;
    } 
    
      protected void guardarDatos() {
          
          metDeInt.setMedida_R(Integer.valueOf(String.valueOf(jftxMedida_R.getValue())));
          metDeInt.setMedida_f(Integer.valueOf(String.valueOf(jftxMedida_f.getValue())));
          metDeInt.setMedida_g(Integer.valueOf(String.valueOf(jftxMedida_g.getValue())));
          metDeInt.setRangoInterior(Integer.valueOf(String.valueOf(jftxRangoInterior.getValue())));
          metDeInt.setMetricaInterior(Integer.valueOf(String.valueOf(jftxMetricaInterior.getValue())));
          metDeInt.setPuntosDeMedicion(Integer.valueOf(String.valueOf(jcboxPuntosMedicion.getSelectedItem())));
           
          metDeInt.guardarDatos();
      }
      
      protected void limpiarDatos() {
          
          jftxMedida_R.setValue(null);
          jftxMedida_f.setValue(null);
          jftxMedida_g.setValue(null);
          jftxRangoInterior.setValue(null);
          jftxMetricaInterior.setValue(null);
          jcboxPuntosMedicion.setSelectedIndex(0);
          
          metDeInt.borrarDatos();       
      }
    
    @Override
      protected void actualizarCambio(String id, Object value) {}
}
