/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package appmitutoyo.interfaces;

import jguiextensible.JGuiSimple;
import jguiextensible.JGuiTabbed;

/**
 *
 * @author a31r1z
 */
public class MetricaMicrometricaGUI extends JGuiSimple {

    /**
     * Creates new form MetricaMicrometrica
     */
    public MetricaMicrometricaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMetrMicrometrica = new javax.swing.JPanel();
        lblAvance = new javax.swing.JLabel();
        lblPlanitud = new javax.swing.JLabel();
        lblParalelismo = new javax.swing.JLabel();
        lblPerpendicularidad = new javax.swing.JLabel();
        lblRectitud = new javax.swing.JLabel();
        jtxtAvance = new javax.swing.JTextField();
        jtxtPlanitud = new javax.swing.JTextField();
        jtxtParalelismo = new javax.swing.JTextField();
        jtxtPerpendicularidad = new javax.swing.JTextField();
        jtxtRectitud = new javax.swing.JTextField();

        setName("Metrica micrometrica"); // NOI18N

        panelMetrMicrometrica.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrica Micrometrica"));
        panelMetrMicrometrica.setName("Metrica micrometrica"); // NOI18N

        lblAvance.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblAvance.setText("Avance ± (µm)");

        lblPlanitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPlanitud.setText("Planitud (µm)");

        lblParalelismo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblParalelismo.setText("Paralelismo (µm)");

        lblPerpendicularidad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPerpendicularidad.setText("Perpendicularidad (µm)");

        lblRectitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRectitud.setText("Rectitud (µm)");

        javax.swing.GroupLayout panelMetrMicrometricaLayout = new javax.swing.GroupLayout(panelMetrMicrometrica);
        panelMetrMicrometrica.setLayout(panelMetrMicrometricaLayout);
        panelMetrMicrometricaLayout.setHorizontalGroup(
            panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetrMicrometricaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMetrMicrometricaLayout.createSequentialGroup()
                        .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblParalelismo)
                            .addComponent(lblPerpendicularidad)
                            .addComponent(lblRectitud)
                            .addComponent(lblPlanitud))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtParalelismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPlanitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPerpendicularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtRectitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMetrMicrometricaLayout.createSequentialGroup()
                        .addComponent(lblAvance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMetrMicrometricaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtAvance, jtxtParalelismo, jtxtPerpendicularidad, jtxtPlanitud, jtxtRectitud});

        panelMetrMicrometricaLayout.setVerticalGroup(
            panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetrMicrometricaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvance)
                    .addComponent(jtxtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlanitud)
                    .addComponent(jtxtPlanitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParalelismo)
                    .addComponent(jtxtParalelismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerpendicularidad)
                    .addComponent(jtxtPerpendicularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRectitud)
                    .addComponent(jtxtRectitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelMetrMicrometrica);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtxtAvance;
    private javax.swing.JTextField jtxtParalelismo;
    private javax.swing.JTextField jtxtPerpendicularidad;
    private javax.swing.JTextField jtxtPlanitud;
    private javax.swing.JTextField jtxtRectitud;
    private javax.swing.JLabel lblAvance;
    private javax.swing.JLabel lblParalelismo;
    private javax.swing.JLabel lblPerpendicularidad;
    private javax.swing.JLabel lblPlanitud;
    private javax.swing.JLabel lblRectitud;
    private javax.swing.JPanel panelMetrMicrometrica;
    // End of variables declaration//GEN-END:variables
@Override
    protected void actualizarCambio(String id, Object obj) {}
}
