/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package mitutoyo.interfaces;

import jguiextensible.JGuiSimple;
import mitutoyo.data.Especificaciones;

/**
 *
 * @author a31r1z
 */
public class EspecificacionesGUI extends JGuiSimple {

    private final Especificaciones especificaciones = new Especificaciones();
    /**
     * Creates new form EspecificacionesGUI
     */
    public EspecificacionesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        articuloGUI1 = new mitutoyo.interfaces.ArticuloGUI();
        dimensionesGUI1 = new mitutoyo.interfaces.DimensionesGUI();

        setName("Especificaciones"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(articuloGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addComponent(dimensionesGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(articuloGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(dimensionesGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        getAccessibleContext().setAccessibleName("Especificaciones");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mitutoyo.interfaces.ArticuloGUI articuloGUI1;
    private mitutoyo.interfaces.DimensionesGUI dimensionesGUI1;
    // End of variables declaration//GEN-END:variables
   
    @Override
    protected boolean validateData() {
            
        return articuloGUI1.validateData() && dimensionesGUI1.validateData();
               
   }
    
    @Override
    protected void saveData() {
        
        articuloGUI1.saveData();
        dimensionesGUI1.saveData();
        
        especificaciones.guardarDatos();
        
  }
  
    @Override
  protected void cleanData() {
  
      articuloGUI1.cleanData();
      dimensionesGUI1.cleanData();
      
      especificaciones.borrarDatos();
      
  }
  
    @Override
     protected void updateChanges(String id, Object value) {}

}
