/**
 * AppMitutoyo is an application to show how works the implementation of the library JGuiExtensible
 * that develops a reusable gui pattern.
 * 
 * Copyright (C) 2022 Alberto Eiriz Lopez
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
*/
package mitutoyo.interfaces;

import mitutoyo.Utilidades;
import mitutoyo.data.MetricaComparativa;
import jguiextensible.JGuiSimple;

/**
 * This class creates a graphical interface for the data structure with the same name
 * 
 * @author a31r1z
 */
public class MetricaComparativaGUI extends JGuiSimple {

    private static final long serialVersionUID = 1L;
   
    private MetricaComparativa metDeComp = new MetricaComparativa();
   
    /**
     * Creates new form MetricaComparador
     */
    public MetricaComparativaGUI() {
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jguiMetricaComp = new jguiextensible.JGuiSimple();
        jftxErrorMax = new javax.swing.JFormattedTextField();
        jsldRangoMedida = new javax.swing.JSlider();
        lblErrorMaximo = new javax.swing.JLabel();
        lblRangoMedida = new javax.swing.JLabel();
        lblHyteresis = new javax.swing.JLabel();
        jftxHyteresis = new javax.swing.JFormattedTextField();
        jftxEscala = new javax.swing.JFormattedTextField();
        lblEscala = new javax.swing.JLabel();

        setName("Metrica Comparador"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jguiMetricaComp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metrica comparativa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Sans", 1, 12))); // NOI18N
        jguiMetricaComp.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxErrorMax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxErrorMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxErrorMax.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jsldRangoMedida.setFont(new java.awt.Font("URW Gothic", 0, 12)); // NOI18N
        jsldRangoMedida.setMajorTickSpacing(10);
        jsldRangoMedida.setMaximum(50);
        jsldRangoMedida.setMinorTickSpacing(5);
        jsldRangoMedida.setPaintLabels(true);
        jsldRangoMedida.setPaintTicks(true);
        jsldRangoMedida.setSnapToTicks(true);
        jsldRangoMedida.setValue(25);
        jsldRangoMedida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldRangoMedidaStateChanged(evt);
            }
        });

        lblErrorMaximo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblErrorMaximo.setText("Error max. permitido");

        lblRangoMedida.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRangoMedida.setText("Rango de medida");

        lblHyteresis.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblHyteresis.setText("Hyteresis (mm)");

        jftxHyteresis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxHyteresis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxHyteresis.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxEscala.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxEscala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxEscala.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        lblEscala.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblEscala.setText("Escala");

        javax.swing.GroupLayout jguiMetricaCompLayout = new javax.swing.GroupLayout(jguiMetricaComp);
        jguiMetricaComp.setLayout(jguiMetricaCompLayout);
        jguiMetricaCompLayout.setHorizontalGroup(
            jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHyteresis)
                    .addComponent(lblEscala)
                    .addComponent(lblRangoMedida)
                    .addComponent(lblErrorMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsldRangoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxErrorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxHyteresis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jguiMetricaCompLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxErrorMax, jftxEscala, jftxHyteresis});

        jguiMetricaCompLayout.setVerticalGroup(
            jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jguiMetricaCompLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblRangoMedida)
                    .addComponent(jsldRangoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblErrorMaximo)
                    .addComponent(jftxErrorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblHyteresis)
                    .addComponent(jftxHyteresis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jguiMetricaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEscala)
                    .addComponent(jftxEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jguiMetricaCompLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jftxErrorMax, jftxEscala, jftxHyteresis});

        add(jguiMetricaComp);
    }// </editor-fold>//GEN-END:initComponents

    private void jsldRangoMedidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldRangoMedidaStateChanged
           System.out.println("Notificacion RangoMedida");
        
        metDeComp.setRangoDeMedida(jsldRangoMedida.getValue());
        notifyChanges("rangoMedida", jsldRangoMedida.getValue());
    }//GEN-LAST:event_jsldRangoMedidaStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JFormattedTextField jftxErrorMax;
    javax.swing.JFormattedTextField jftxEscala;
    javax.swing.JFormattedTextField jftxHyteresis;
    jguiextensible.JGuiSimple jguiMetricaComp;
    javax.swing.JSlider jsldRangoMedida;
    javax.swing.JLabel lblErrorMaximo;
    javax.swing.JLabel lblEscala;
    javax.swing.JLabel lblHyteresis;
    javax.swing.JLabel lblRangoMedida;
    // End of variables declaration//GEN-END:variables


    /**
     * Validates the data inserted in the diferent widgets of the gui
     * 
     * @return true of false if data inserted in the fields are valid
     */
    @Override
    protected boolean validateData() {
        
        return Utilidades.matcher(jftxErrorMax, "ErrorMax",this) &&
               Utilidades.matcher(jftxHyteresis, "Hyteresis",this) &&
               Utilidades.matcher(jftxEscala, "Escala",this);   
    }
   
    /**
     * Saves the data inserted in the gui
     */
    @Override
     protected void saveData() {
     
         metDeComp.setErrorMaximo(Integer.valueOf(String.valueOf(jftxErrorMax.getValue())));
         metDeComp.setHyteresis(Integer.valueOf(String.valueOf(jftxHyteresis.getValue())));
         metDeComp.setEscala(Integer.valueOf(String.valueOf(jftxEscala.getValue())));
         metDeComp.setRangoDeMedida(Integer.valueOf(String.valueOf(jsldRangoMedida.getValue())));
         
         metDeComp.guardarDatos();
     }
     
     /**
     * Cleans the data inserted in the widgets of the gui
     */
    @Override
     protected void cleanData() {
         
         jftxErrorMax.setValue(null);
         jftxHyteresis.setValue(null);
         jftxEscala.setValue(null);
         jsldRangoMedida.setValue(25);
         
         metDeComp.borrarDatos();              
     }
     
     /**
     * Updates the value of diferent widgets notified by other component whose name is id.
     * 
     * @param id name of the component that notifies a change in his value
     * @param value value that changes
     */
       @Override
     protected void updateChanges(String id, Object value) {}

}
