/**
 * AppMitutoyo is an application to show how works the implementation of the library JGuiExtensible
 * that develops a reusable gui pattern.
 * 
 * Copyright (C) 2022 Alberto Eiriz Lopez
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
*/
package mitutoyo.interfaces;

import mitutoyo.Utilidades;
import mitutoyo.data.MetricaMicrometrica;
import jguiextensible.JGuiSimple;

/**
 * This class creates a graphical interface for the data structure with the same name
 * 
 * @author a31r1z
 */
public class MetricaMicrometricaGUI extends JGuiSimple {

    private static final long serialVersionUID = 1L;
    
    private final MetricaMicrometrica metMicro = new MetricaMicrometrica();

    /**
     * Creates new form MetricaMicrometrica
     */
    public MetricaMicrometricaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMetrMicrometrica = new javax.swing.JPanel();
        lblAvance = new javax.swing.JLabel();
        lblPlanitud = new javax.swing.JLabel();
        lblParalelismo = new javax.swing.JLabel();
        lblPerpendicularidad = new javax.swing.JLabel();
        lblRectitud = new javax.swing.JLabel();
        jftxAvance = new javax.swing.JFormattedTextField();
        jftxPlanitud = new javax.swing.JFormattedTextField();
        jftxParalelismo = new javax.swing.JFormattedTextField();
        jftxPerpendicularidad = new javax.swing.JFormattedTextField();
        jftxRectitud = new javax.swing.JFormattedTextField();

        setName("Metrica micrometrica"); // NOI18N

        panelMetrMicrometrica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metrica Micrometrica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Sans", 1, 12))); // NOI18N
        panelMetrMicrometrica.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        panelMetrMicrometrica.setName("Metrica micrometrica"); // NOI18N

        lblAvance.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblAvance.setText("Avance ± (µm)");

        lblPlanitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPlanitud.setText("Planitud (µm)");

        lblParalelismo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblParalelismo.setText("Paralelismo (µm)");

        lblPerpendicularidad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPerpendicularidad.setText("Perpendicularidad (µm)");

        lblRectitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblRectitud.setText("Rectitud (µm)");

        jftxAvance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxAvance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxAvance.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxPlanitud.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxPlanitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxPlanitud.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftxPlanitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxParalelismo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxParalelismo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxParalelismo.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxPerpendicularidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxPerpendicularidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxPerpendicularidad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxRectitud.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxRectitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxRectitud.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        javax.swing.GroupLayout panelMetrMicrometricaLayout = new javax.swing.GroupLayout(panelMetrMicrometrica);
        panelMetrMicrometrica.setLayout(panelMetrMicrometricaLayout);
        panelMetrMicrometricaLayout.setHorizontalGroup(
            panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetrMicrometricaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParalelismo)
                    .addComponent(lblPlanitud)
                    .addComponent(lblRectitud)
                    .addComponent(lblPerpendicularidad)
                    .addComponent(lblAvance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxPlanitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxParalelismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxPerpendicularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxRectitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMetrMicrometricaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxAvance, jftxParalelismo, jftxPerpendicularidad, jftxPlanitud, jftxRectitud});

        panelMetrMicrometricaLayout.setVerticalGroup(
            panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetrMicrometricaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvance)
                    .addComponent(jftxAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlanitud)
                    .addComponent(jftxPlanitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParalelismo)
                    .addComponent(jftxParalelismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerpendicularidad)
                    .addComponent(jftxPerpendicularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelMetrMicrometricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRectitud)
                    .addComponent(jftxRectitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelMetrMicrometrica);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jftxAvance;
    private javax.swing.JFormattedTextField jftxParalelismo;
    private javax.swing.JFormattedTextField jftxPerpendicularidad;
    private javax.swing.JFormattedTextField jftxPlanitud;
    private javax.swing.JFormattedTextField jftxRectitud;
    private javax.swing.JLabel lblAvance;
    private javax.swing.JLabel lblParalelismo;
    private javax.swing.JLabel lblPerpendicularidad;
    private javax.swing.JLabel lblPlanitud;
    private javax.swing.JLabel lblRectitud;
    private javax.swing.JPanel panelMetrMicrometrica;
    // End of variables declaration//GEN-END:variables

    /**
     * Validates the data inserted in the diferent widgets of the gui
     * 
     * @return true of false if data inserted in the fields are valid
     */
    @Override
    protected boolean validateData( ) {
             
    return  Utilidades.matcher(jftxAvance, "Avance",this) &&
            Utilidades.matcher(jftxPlanitud, "Planitud",this) &&
            Utilidades.matcher(jftxParalelismo, "Paralelismo",this) &&
            Utilidades.matcher(jftxPerpendicularidad, "Perpendicularidad",this) &&
            Utilidades.matcher(jftxRectitud, "Rectitud",this) ;
    }
 
    /**
     * Saves the data inserted in the gui
     */
    @Override
    protected void saveData() {
        
        metMicro.setAvance(Integer.valueOf(String.valueOf(jftxAvance.getValue())));
        metMicro.setParalelismo(Integer.valueOf(String.valueOf(jftxParalelismo.getValue())));
        metMicro.setPerpendicularidad(Integer.valueOf(String.valueOf(jftxPerpendicularidad.getValue())));
        metMicro.setPlanitud(Integer.valueOf(String.valueOf(jftxPlanitud.getValue())));
        metMicro.setRectitud(Integer.valueOf(String.valueOf(jftxRectitud.getValue())));
        
        metMicro.guardarDatos();
    }
    
    /**
     * Cleans the data inserted in the widgets of the gui
     */
    @Override
    protected void cleanData() {
        
        jftxAvance.setValue(null);
        jftxParalelismo.setValue(null);
        jftxPerpendicularidad.setValue(null);
        jftxPlanitud.setValue(null);
        jftxRectitud.setValue(null);
        
        metMicro.borrarDatos();
    }
    
    /**
     * Updates the value of diferent widgets notified by other component whose name is id.
     * 
     * @param id name of the component that notifies a change in his value
     * @param value value that changes
     */
    @Override
    protected void updateChanges(String id, Object value) {
     
             System.out.println("Actualizando Avance");
        switch(id) {
            case "rangoMedida" -> { jftxAvance.setValue(value); }
        }
    }

}
