/**
 * AppMitutoyo is an application to show how works the implementation of the library JGuiExtensible
 * that develops a reusable gui pattern.
 * 
 * Copyright (C) 2022 Alberto Eiriz Lopez
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
*/
package mitutoyo.interfaces;

import mitutoyo.Utilidades;
import mitutoyo.data.Singularidad;

/**
 * This class creates a graphical interface for the data structure with the same name
 * 
 * @author a31r1z
 */
public class SingularidadGUI extends jguiextensible.JGuiSimple {

    private static final long serialVersionUID = 1L;
    
    private Singularidad sing = new Singularidad();

    /**
     * Creates new SingularidadGUI form JGuiSimple
     */
    public SingularidadGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGuiSimple1 = new jguiextensible.JGuiSimple();
        jftxtSingularidad = new javax.swing.JFormattedTextField();
        lblMargen = new javax.swing.JLabel();
        jsldMargen = new javax.swing.JSlider();
        lblSingularidad = new javax.swing.JLabel();
        lblLimite = new javax.swing.JLabel();
        jftxtLimite = new javax.swing.JFormattedTextField();
        jGuiSimple2 = new jguiextensible.JGuiSimple();
        lblPromedio = new javax.swing.JLabel();
        jftxtPromedio = new javax.swing.JFormattedTextField();
        lblMediana = new javax.swing.JLabel();
        jftxtMediana = new javax.swing.JFormattedTextField();
        lblValorRef = new javax.swing.JLabel();
        jftxtValorRef = new javax.swing.JFormattedTextField();
        jGuiSimple3 = new jguiextensible.JGuiSimple();
        lblDesvMedia = new javax.swing.JLabel();
        lblDesvTipica = new javax.swing.JLabel();
        lblDesvAbsoluta = new javax.swing.JLabel();
        jftxtDesvMedia = new javax.swing.JFormattedTextField();
        jftxtDesvTipica = new javax.swing.JFormattedTextField();
        jftxtDesvAbsoluta = new javax.swing.JFormattedTextField();

        setName("Singularidad"); // NOI18N

        jGuiSimple1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Singularidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Sans", 1, 12))); // NOI18N
        jGuiSimple1.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jGuiSimple1.setName("Singularidad"); // NOI18N

        jftxtSingularidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtSingularidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtSingularidad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        lblMargen.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMargen.setText("Margen");

        jsldMargen.setFont(new java.awt.Font("URW Gothic", 0, 10)); // NOI18N
        jsldMargen.setMajorTickSpacing(10);
        jsldMargen.setMinorTickSpacing(5);
        jsldMargen.setPaintLabels(true);
        jsldMargen.setPaintTicks(true);
        jsldMargen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldMargenStateChanged(evt);
            }
        });

        lblSingularidad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblSingularidad.setText("Singularidad ");

        lblLimite.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblLimite.setText("Limite");

        jftxtLimite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtLimite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtLimite.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jGuiSimple2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desviacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Sans", 1, 12))); // NOI18N
        jGuiSimple2.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jGuiSimple2.setName("Desviacion"); // NOI18N

        lblPromedio.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblPromedio.setText("Promedio");

        jftxtPromedio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtPromedio.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        lblMediana.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblMediana.setText("Mediana");

        jftxtMediana.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtMediana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtMediana.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        lblValorRef.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblValorRef.setText("Valor Ref.");

        jftxtValorRef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtValorRef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtValorRef.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        javax.swing.GroupLayout jGuiSimple2Layout = new javax.swing.GroupLayout(jGuiSimple2);
        jGuiSimple2.setLayout(jGuiSimple2Layout);
        jGuiSimple2Layout.setHorizontalGroup(
            jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuiSimple2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorRef, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(lblPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxtMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtValorRef, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jGuiSimple2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxtMediana, jftxtPromedio, jftxtValorRef});

        jGuiSimple2Layout.setVerticalGroup(
            jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuiSimple2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMediana)
                    .addComponent(jftxtMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorRef)
                    .addComponent(jftxtValorRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jGuiSimple2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromedio)
                    .addComponent(jftxtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jGuiSimple3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dispersion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Sans", 1, 12))); // NOI18N
        jGuiSimple3.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jGuiSimple3.setName("Dispersion"); // NOI18N

        lblDesvMedia.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblDesvMedia.setText("Desv. Media");

        lblDesvTipica.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblDesvTipica.setText("Desv. Tipica");

        lblDesvAbsoluta.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        lblDesvAbsoluta.setText("Desv. Absoluta");

        jftxtDesvMedia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtDesvMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtDesvMedia.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxtDesvTipica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtDesvTipica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtDesvTipica.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jftxtDesvAbsoluta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftxtDesvAbsoluta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtDesvAbsoluta.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        javax.swing.GroupLayout jGuiSimple3Layout = new javax.swing.GroupLayout(jGuiSimple3);
        jGuiSimple3.setLayout(jGuiSimple3Layout);
        jGuiSimple3Layout.setHorizontalGroup(
            jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuiSimple3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesvTipica)
                    .addComponent(lblDesvAbsoluta)
                    .addComponent(lblDesvMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxtDesvMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtDesvAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtDesvTipica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jGuiSimple3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jftxtDesvAbsoluta, jftxtDesvMedia, jftxtDesvTipica});

        jGuiSimple3Layout.setVerticalGroup(
            jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuiSimple3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesvMedia)
                    .addComponent(jftxtDesvMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesvTipica)
                    .addComponent(jftxtDesvTipica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jGuiSimple3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDesvAbsoluta)
                    .addComponent(jftxtDesvAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jGuiSimple3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jftxtDesvAbsoluta, jftxtDesvMedia, jftxtDesvTipica});

        javax.swing.GroupLayout jGuiSimple1Layout = new javax.swing.GroupLayout(jGuiSimple1);
        jGuiSimple1.setLayout(jGuiSimple1Layout);
        jGuiSimple1Layout.setHorizontalGroup(
            jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuiSimple1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMargen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jGuiSimple1Layout.createSequentialGroup()
                        .addComponent(lblSingularidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jGuiSimple1Layout.createSequentialGroup()
                        .addComponent(jftxtSingularidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftxtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jsldMargen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jGuiSimple1Layout.createSequentialGroup()
                .addComponent(jGuiSimple2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGuiSimple3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jGuiSimple1Layout.setVerticalGroup(
            jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuiSimple1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMargen)
                    .addComponent(jsldMargen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jftxtSingularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSingularidad))
                    .addComponent(lblLimite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jftxtLimite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jGuiSimple1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuiSimple3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jGuiSimple2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jGuiSimple1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jGuiSimple1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jsldMargenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldMargenStateChanged
        System.out.println("Notificacion Margen");
        jftxtDesvMedia.setValue(jsldMargen.getValue());
        
        sing.setMargen(jsldMargen.getValue());
        notifyChanges("margen",jsldMargen.getValue());
      
    }//GEN-LAST:event_jsldMargenStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jguiextensible.JGuiSimple jGuiSimple1;
    private jguiextensible.JGuiSimple jGuiSimple2;
    private jguiextensible.JGuiSimple jGuiSimple3;
    private javax.swing.JFormattedTextField jftxtDesvAbsoluta;
    private javax.swing.JFormattedTextField jftxtDesvMedia;
    private javax.swing.JFormattedTextField jftxtDesvTipica;
    private javax.swing.JFormattedTextField jftxtLimite;
    private javax.swing.JFormattedTextField jftxtMediana;
    private javax.swing.JFormattedTextField jftxtPromedio;
    private javax.swing.JFormattedTextField jftxtSingularidad;
    private javax.swing.JFormattedTextField jftxtValorRef;
    private javax.swing.JSlider jsldMargen;
    private javax.swing.JLabel lblDesvAbsoluta;
    private javax.swing.JLabel lblDesvMedia;
    private javax.swing.JLabel lblDesvTipica;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblMargen;
    private javax.swing.JLabel lblMediana;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblSingularidad;
    private javax.swing.JLabel lblValorRef;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Validates the data inserted in the diferent widgets of the gui
     * 
     * @return true of false if data inserted in the fields are valid
     */
    @Override
    protected boolean validateData() {        
        
        return Utilidades.matcher(jftxtSingularidad, "Singularidad", this)
                && Utilidades.matcher(jftxtLimite, "Limite", this)
                && Utilidades.matcher(jftxtMediana, "Mediana", this)
                && Utilidades.matcher(jftxtValorRef, "ValorRef", this)
                && Utilidades.matcher(jftxtPromedio, "Promedio", this)
                && Utilidades.matcher(jftxtDesvMedia, "Desv.Media", this)
                && Utilidades.matcher(jftxtDesvTipica, "Desv.Tipica", this)
                && Utilidades.matcher(jftxtDesvAbsoluta, "Desv.Absoluta", this);
                            
    }

    /**
     * Saves the data inserted in the gui
     */
    @Override
    protected void saveData() {
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jsldMargen.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtSingularidad.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtLimite.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtMediana.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtValorRef.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtPromedio.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtDesvMedia.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtDesvTipica.getValue())));
        sing.setDesvAbsoluta(Integer.valueOf(String.valueOf(jftxtDesvAbsoluta.getValue())));

        sing.guardarDatos();
    }

    /**
     * Cleans the data inserted in the widgets of the gui
     */
    @Override
    protected void cleanData() {
        
         jsldMargen.setValue(50);
         jftxtDesvAbsoluta.setValue(null);
         jftxtDesvMedia.setValue(null);
         jftxtDesvTipica.setValue(null);
         jftxtLimite.setValue(null);
         jftxtMediana.setValue(null);
         jftxtPromedio.setValue(null);
         jftxtSingularidad.setValue(null);
         jftxtValorRef.setValue(null);
         
         sing.borrarDatos();
    }

    /**
     * Updates the value of diferent widgets notified by other component whose name is id.
     * 
     * @param id name of the component that notifies a change in his value
     * @param value value that changes
     */
    @Override
    protected void updateChanges(String id, Object value) {
        
    }
}
